spring:
  application:
    name: student-backend
  datasource:
    url: jdbc:mysql://db:3306/student_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: baby
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection:
          useUnicode: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    '[com.company.project]': DEBUG
    '[org.springframework.web]': DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
